/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as afyaSol from "./Afya.sol";
export type { afyaSol };
import type * as afyappSol from "./Afyapp.sol";
export type { afyappSol };
export type { AppointmentManagement } from "./AppointmentManagement";
export type { MedicalExperts } from "./MedicalExperts";
export type { PatientManagement } from "./PatientManagement";
export type { RecordAccess } from "./RecordAccess";
