/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as afyaSol from "./Afya.sol";
export * as afyappSol from "./Afyapp.sol";
export { AppointmentManagement__factory } from "./AppointmentManagement__factory";
export { MedicalExperts__factory } from "./MedicalExperts__factory";
export { PatientManagement__factory } from "./PatientManagement__factory";
export { RecordAccess__factory } from "./RecordAccess__factory";
